language: objective-c

env:
  matrix:
    - SCHEME=FontAwesomeIconFactoryDemo
    - SCHEME=FontAwesomeIconFactoryDemoOSX

script:
  - xctool -workspace *.xcworkspace -scheme $SCHEME build test CODE_SIGN_IDENTITY="" ONLY_ACTIVE_ARCH=NO

notifications:
  email: false
